from io import BytesIO
from datetime import date

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
)


class PDFReportService:

    # =========================================================
    # HELPERS
    # =========================================================

    @staticmethod
    def _format_date(value):
        if value is None:
            return "-"

        if isinstance(value, date):
            return value.strftime("%d %b %Y")

        return str(value)

    @staticmethod
    def _score(value):
        if value is None:
            return "-"

        try:
            return f"{float(value):.2f}"
        except (TypeError, ValueError):
            return str(value)

    @staticmethod
    def _percentage(score):
        """
        Scores in database are 0-10.
        Convert to percentage for visual report.
        """
        if score is None:
            return "-"

        try:
            return f"{float(score) * 10:.1f}%"
        except (TypeError, ValueError):
            return "-"

    @staticmethod
    def _safe_text(value):
        if value is None:
            return ""

        return str(value).replace("&", "&amp;").replace(
            "<", "&lt;"
        ).replace(">", "&gt;")

    # =========================================================
    # HEADER / FOOTER
    # =========================================================

    @staticmethod
    def _header_footer(canvas, doc):
        canvas.saveState()

        width, height = A4

        # Header line
        canvas.setStrokeColor(colors.HexColor("#D1D5DB"))
        canvas.setLineWidth(0.5)

        canvas.line(
            18 * mm,
            height - 12 * mm,
            width - 18 * mm,
            height - 12 * mm,
        )

        # Header text
        canvas.setFont("Helvetica-Bold", 8)
        canvas.setFillColor(colors.HexColor("#1F4E79"))

        canvas.drawString(
            18 * mm,
            height - 9 * mm,
            "VoiceInsights AI",
        )

        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#6B7280"))

        canvas.drawRightString(
            width - 18 * mm,
            height - 9 * mm,
            "Performance Analytics",
        )

        # Footer line
        canvas.setStrokeColor(colors.HexColor("#D1D5DB"))

        canvas.line(
            18 * mm,
            14 * mm,
            width - 18 * mm,
            14 * mm,
        )

        canvas.setFont("Helvetica", 7.5)
        canvas.setFillColor(colors.HexColor("#6B7280"))

        canvas.drawString(
            18 * mm,
            8.5 * mm,
            "Generated by VoiceInsights AI",
        )

        canvas.drawRightString(
            width - 18 * mm,
            8.5 * mm,
            f"Page {doc.page}",
        )

        canvas.restoreState()

    # =========================================================
    # STYLES
    # =========================================================

    @staticmethod
    def _styles():

        styles = getSampleStyleSheet()

        return {
            "title": ParagraphStyle(
                "ReportTitle",
                parent=styles["Title"],
                fontName="Helvetica-Bold",
                fontSize=22,
                leading=26,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#17365D"),
                spaceAfter=5,
            ),

            "subtitle": ParagraphStyle(
                "ReportSubtitle",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=10,
                leading=14,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#6B7280"),
                spaceAfter=16,
            ),

            "section": ParagraphStyle(
                "Section",
                parent=styles["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=14,
                leading=18,
                textColor=colors.HexColor("#17365D"),
                spaceBefore=12,
                spaceAfter=8,
            ),

            "normal": ParagraphStyle(
                "ReportNormal",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                leading=12,
                textColor=colors.HexColor("#374151"),
            ),

            "small": ParagraphStyle(
                "Small",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=7.5,
                leading=10,
                textColor=colors.HexColor("#4B5563"),
            ),

            "table_header": ParagraphStyle(
                "TableHeader",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8,
                leading=10,
                textColor=colors.white,
            ),

            "table_text": ParagraphStyle(
                "TableText",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=7.5,
                leading=10,
                textColor=colors.HexColor("#374151"),
            ),

            "kpi_value": ParagraphStyle(
                "KPIValue",
                parent=styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=17,
                leading=20,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#17365D"),
            ),

            "kpi_label": ParagraphStyle(
                "KPILabel",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=7.5,
                leading=10,
                alignment=TA_CENTER,
                textColor=colors.HexColor("#6B7280"),
            ),

            "recommendation": ParagraphStyle(
                "Recommendation",
                parent=styles["Normal"],
                fontName="Helvetica",
                fontSize=8,
                leading=11,
                textColor=colors.HexColor("#374151"),
            ),
        }

    # =========================================================
    # TABLE BUILDER
    # =========================================================

    @staticmethod
    def _table(
        data,
        widths=None,
        font_size=8,
        header_background="#1F4E79",
        repeat_rows=1,
    ):

        table = Table(
            data,
            colWidths=widths,
            repeatRows=repeat_rows,
            hAlign="LEFT",
        )

        table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.HexColor(header_background),
                    ),
                    (
                        "TEXTCOLOR",
                        (0, 0),
                        (-1, 0),
                        colors.white,
                    ),
                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold",
                    ),
                    (
                        "FONTSIZE",
                        (0, 0),
                        (-1, -1),
                        font_size,
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        colors.HexColor("#D1D5DB"),
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        6,
                    ),
                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        6,
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        5,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        5,
                    ),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [
                            colors.white,
                            colors.HexColor("#F8FAFC"),
                        ],
                    ),
                ]
            )
        )

        return table

    # =========================================================
    # KPI CARD
    # =========================================================

    @staticmethod
    def _kpi_card(label, value):

        data = [
            [
                Paragraph(
                    str(value),
                    PDFReportService._styles()["kpi_value"],
                )
            ],
            [
                Paragraph(
                    str(label),
                    PDFReportService._styles()["kpi_label"],
                )
            ],
        ]

        table = Table(
            data,
            colWidths=[39 * mm],
            rowHeights=[12 * mm, 9 * mm],
        )

        table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, -1),
                        colors.HexColor("#F3F7FB"),
                    ),
                    (
                        "BOX",
                        (0, 0),
                        (-1, -1),
                        0.7,
                        colors.HexColor("#C8D6E5"),
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "ALIGN",
                        (0, 0),
                        (-1, -1),
                        "CENTER",
                    ),
                ]
            )
        )

        return table

    # =========================================================
    # GENERATE PDF
    # =========================================================

    @staticmethod
    def generate_pdf(report_data: dict) -> BytesIO:

        buffer = BytesIO()

        document = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=18 * mm,
            leftMargin=18 * mm,
            topMargin=20 * mm,
            bottomMargin=20 * mm,
            title="VoiceInsights Performance Report",
            author="VoiceInsights AI",
        )

        styles = PDFReportService._styles()

        story = []

        # =====================================================
        # DATA
        # =====================================================

        period = report_data.get(
            "report_period",
            report_data.get("period", {}),
        )

        start_date = period.get("start_date")
        end_date = period.get("end_date")

        summary = report_data.get("summary", {})
        sentiment = report_data.get("sentiment", {})
        rules = report_data.get("rules", {})

        organization = report_data.get("organization") or {}
        team = report_data.get("team") or {}

        daily = report_data.get("daily_performance", [])
        agents = report_data.get("agent_performance", [])
        violations = report_data.get("violations", [])

# ---------------------------------------------------------
# Calling agent
# ---------------------------------------------------------
# agent_performance contains ONLY actual calling agents.
# If the report is scoped to one agent, this will contain one agent.
# If the report contains multiple calling agents, we show "Multiple".
        calling_agent = None

        if len(agents) == 1:
            calling_agent = agents[0]
        # =====================================================
        # TITLE
        # =====================================================

        story.append(
            Spacer(1, 8 * mm)
        )

        story.append(
            Paragraph(
                "VoiceInsights Performance Report",
                styles["title"],
            )
        )

        story.append(
            Paragraph(
                "AI-Powered Call Quality & Agent Performance Analysis",
                styles["subtitle"],
            )
        )

        # =====================================================
        # REPORT INFORMATION
        # =====================================================

        agent_name = (
            calling_agent.get("agent_name")
            if calling_agent
            else "Multiple Calling Agents"
        )

        organization_name = (
            organization.get("name")
            or (
                calling_agent.get("organization_name")
                if calling_agent
                else None
            )
            or "N/A"
        )

        team_name = (
            team.get("name")
            or (
                calling_agent.get("team_name")
                if calling_agent
                else None
           )
           or "N/A"
        )

        info_data = [
            [
                Paragraph(
                    "<b>Organization</b>",
                    styles["normal"],
                ),
                Paragraph(
                    PDFReportService._safe_text(
                        organization_name
                    ),
                    styles["normal"],
               ),
            ],
            [
                Paragraph(
                    "<b>Team</b>",
                    styles["normal"],
                ),
                Paragraph(
                    PDFReportService._safe_text(
                        team_name
                    ),
                    styles["normal"],
               ),
            ],
            [
                Paragraph(
                    "<b>Calling Agent</b>",
                    styles["normal"],
                ),
                Paragraph(
                    PDFReportService._safe_text(
                        agent_name
                    ),
                    styles["normal"],
                ),
            ],
            [
                Paragraph(
                    "<b>Report Period</b>",
                    styles["normal"],
                ),
                Paragraph(
                    f"{PDFReportService._format_date(start_date)} "
                    f"to "
                    f"{PDFReportService._format_date(end_date)}",
                    styles["normal"],
                ),
            ],
            [
                Paragraph(
                    "<b>Report Type</b>",
                    styles["normal"],
                ),
                Paragraph(
                    "Calling Agent Performance Report",
                    styles["normal"],
                ),
            ],
        ]  

        info_table = Table(
            info_data,
            colWidths=[40 * mm, 135 * mm],
        )

        info_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (0, -1),
                        colors.HexColor("#EEF3F8"),
                    ),
                    (
                        "BOX",
                        (0, 0),
                        (-1, -1),
                        0.5,
                        colors.HexColor("#D1D5DB"),
                    ),
                    (
                        "INNERGRID",
                        (0, 0),
                        (-1, -1),
                        0.3,
                        colors.HexColor("#E5E7EB"),
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "MIDDLE",
                    ),
                    (
                        "LEFTPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "RIGHTPADDING",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        6,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        6,
                    ),
                ]
            )
        )

        story.append(info_table)

        # =====================================================
        # EXECUTIVE SUMMARY
        # =====================================================

        story.append(
            Paragraph(
                "1. Executive Summary",
                styles["section"],
            )
        )

        kpi_data = [
            [
                PDFReportService._kpi_card(
                    "Total Calls",
                    summary.get("total_calls", 0),
                ),
                PDFReportService._kpi_card(
                    "Analyzed Calls",
                    summary.get("analyzed_calls", 0),
                ),
                PDFReportService._kpi_card(
                    "Overall Score",
                    PDFReportService._score(
                        summary.get("average_overall_score")
                    ),
                ),
                PDFReportService._kpi_card(
                    "Compliance",
                    PDFReportService._percentage(
                        summary.get("average_compliance")
                    ),
                ),
            ]
        ]

        kpi_table = Table(
            kpi_data,
            colWidths=[
                43 * mm,
                43 * mm,
                43 * mm,
                43 * mm,
            ],
        )

        kpi_table.setStyle(
            TableStyle(
                [
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 2),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 2),
                ]
            )
        )

        story.append(kpi_table)
        story.append(Spacer(1, 5 * mm))

        # =====================================================
        # AGENT  PERFORMANCE OVERVIEW
        # =====================================================

        story.append(
            Paragraph(
                "2. Agent Performance Overview",
                styles["section"],
            )
        )

        performance_data = [
            [
                "Performance Metric",
                "Average Score",
                "Percentage",
            ],
            [
                "Agent Performance Overview",
                PDFReportService._score(
                    summary.get("average_overall_score")
                ),
                PDFReportService._percentage(
                    summary.get("average_overall_score")
                ),
            ],
            [
                "Compliance",
                PDFReportService._score(
                    summary.get("average_compliance")
                ),
                PDFReportService._percentage(
                    summary.get("average_compliance")
                ),
            ],
            [
                "Professionalism",
                PDFReportService._score(
                    summary.get("average_professionalism")
                ),
                PDFReportService._percentage(
                    summary.get("average_professionalism")
                ),
            ],
            [
                "Empathy",
                PDFReportService._score(
                    summary.get("average_empathy")
                ),
                PDFReportService._percentage(
                    summary.get("average_empathy")
                ),
            ],
        ]

        story.append(
            PDFReportService._table(
                performance_data,
                widths=[
                    85 * mm,
                    45 * mm,
                    45 * mm,
                ],
            )
        )

        # =====================================================
        # SENTIMENT
        # =====================================================

        story.append(
            Paragraph(
                "3. Sentiment Analysis",
                styles["section"],
            )
        )

        sentiment_data = [
            [
                "Sentiment",
                "Calls",
                "Share",
            ],
        ]

        total_sentiment = sum(
            int(sentiment.get(key, 0) or 0)
            for key in [
                "positive",
                "neutral",
                "negative",
                "other",
            ]
        )

        for key, label in [
            ("positive", "Positive"),
            ("neutral", "Neutral"),
            ("negative", "Negative"),
            ("other", "Other"),
        ]:

            count = int(sentiment.get(key, 0) or 0)

            percentage = (
                f"{(count / total_sentiment * 100):.1f}%"
                if total_sentiment
                else "0%"
            )

            sentiment_data.append(
                [
                    label,
                    count,
                    percentage,
                ]
            )

        story.append(
            PDFReportService._table(
                sentiment_data,
                widths=[
                    80 * mm,
                    45 * mm,
                    50 * mm,
                ],
            )
        )

        # =====================================================
        # RULE COMPLIANCE
        # =====================================================

        story.append(
            Paragraph(
                "4. Rule Compliance",
                styles["section"],
            )
        )

        rule_data = [
            [
                "Rule",
                "Followed",
                "Not Followed",
                "Compliance Rate",
            ],
            [
                "Greeting",
                rules.get("greeting_followed", 0),
                rules.get("greeting_not_followed", 0),
                PDFReportService._rule_percentage(
                    rules.get("greeting_followed", 0),
                    rules.get("greeting_not_followed", 0),
                ),
            ],
            [
                "Closing",
                rules.get("closing_followed", 0),
                rules.get("closing_not_followed", 0),
                PDFReportService._rule_percentage(
                    rules.get("closing_followed", 0),
                    rules.get("closing_not_followed", 0),
                ),
            ],
        ]

        story.append(
            PDFReportService._table(
                rule_data,
                widths=[
                    60 * mm,
                    35 * mm,
                    40 * mm,
                    40 * mm,
                ],
            )
        )

        # =====================================================
        # DAILY PERFORMANCE
        # =====================================================

        story.append(
            Paragraph(
                "5. Daily Performance",
                styles["section"],
            )
        )

        daily_data = [
            [
                "Date",
                "Calls",
                "Overall",
                "Compliance",
                "Professionalism",
                "Empathy",
                "Violations",
            ]
        ]

        for row in daily:

            daily_data.append(
                [
                    PDFReportService._format_date(
                        row.get("date")
                    ),
                    row.get("calls", 0),
                    PDFReportService._score(
                        row.get("average_overall_score")
                    ),
                    PDFReportService._score(
                        row.get("average_compliance")
                    ),
                    PDFReportService._score(
                        row.get("average_professionalism")
                    ),
                    PDFReportService._score(
                        row.get("average_empathy")
                    ),
                    row.get("violations", 0),
                ]
            )

        if len(daily_data) == 1:

            daily_data.append(
                [
                    "No data",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                ]
            )

        story.append(
            PDFReportService._table(
                daily_data,
                widths=[
                    29 * mm,
                    18 * mm,
                    24 * mm,
                    28 * mm,
                    32 * mm,
                    24 * mm,
                    25 * mm,
                ],
                font_size=7,
            )
        )

        # =====================================================
        # CALLING AGENT PERFORMANCE
        # =====================================================

        story.append(
            Paragraph(
                "6. Calling Agent Performance",
                styles["section"],
            )
        )

        agent_data = [
            [
                "Agent",
                "Calls",
                "Overall",
                "Compliance",
                "Professionalism",
                "Empathy",
                "Violations",
            ]
        ]

        for agent in agents:

            agent_data.append(
                [
                    Paragraph(
                        PDFReportService._safe_text(
                            agent.get("agent_name", "Unknown")
                        ),
                        styles["table_text"],
                    ),
                    agent.get("calls", 0),
                    PDFReportService._score(
                        agent.get("average_overall_score")
                    ),
                    PDFReportService._score(
                        agent.get("average_compliance")
                    ),
                    PDFReportService._score(
                        agent.get("average_professionalism")
                    ),
                    PDFReportService._score(
                        agent.get("average_empathy")
                    ),
                    agent.get("violations", 0),
                ]
            )

        if len(agent_data) == 1:

            agent_data.append(
                [
                    "No data",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                    "-",
                ]
            )

        story.append(
            PDFReportService._table(
                agent_data,
                widths=[
                    40 * mm,
                    18 * mm,
                    23 * mm,
                    25 * mm,
                    31 * mm,
                    22 * mm,
                    20 * mm,
                ],
                font_size=7,
            )
        )

        # =====================================================
        # TOP VIOLATIONS
        # =====================================================

        story.append(
            Paragraph(
                "7. Top Violations",
                styles["section"],
            )
        )

        violation_data = [
            [
                "Violation",
                "Occurrences",
            ]
        ]

        for item in violations:

            violation_text = PDFReportService._safe_text(
                item.get("violation", "")
            )

            violation_data.append(
                [
                    Paragraph(
                        violation_text,
                        styles["table_text"],
                    ),
                    item.get("count", 0),
                ]
            )

        if len(violation_data) == 1:

            violation_data.append(
                [
                    "No violations found",
                    0,
                ]
            )

        story.append(
            PDFReportService._table(
                violation_data,
                widths=[
                    145 * mm,
                    25 * mm,
                ],
            )
        )

        # =====================================================
        # RECOMMENDATIONS
        # =====================================================

        story.append(
            Paragraph(
                "8. Recommendations",
                styles["section"],
            )
        )

        recommendations = PDFReportService._build_recommendations(
            report_data
        )

        recommendation_data = [
            [
                "Priority",
                "Recommendation",
            ]
        ]

        for priority, recommendation in recommendations:

            recommendation_data.append(
                [
                    priority,
                    Paragraph(
                        PDFReportService._safe_text(
                            recommendation
                        ),
                        styles["recommendation"],
                    ),
                ]
            )

        story.append(
            PDFReportService._table(
                recommendation_data,
                widths=[
                    30 * mm,
                    140 * mm,
                ],
            )
        )

        # =====================================================
        # FINAL OBSERVATION
        # =====================================================

        story.append(
            Spacer(1, 6 * mm)
        )

        story.append(
            Paragraph(
                "Report Conclusion",
                styles["section"],
            )
        )

        overall = summary.get(
            "average_overall_score"
        )

        empathy = summary.get(
            "average_empathy"
        )

        conclusion = (
            f"<b>{PDFReportService._safe_text(agent_name)}</b> "
            f"handled <b>{summary.get('total_calls', 0)}</b> calls during "
            f"the selected reporting period, with "
            f"<b>{summary.get('analyzed_calls', 0)}</b> analyzed calls. "
            f"The average overall performance score was "
            f"<b>{PDFReportService._score(overall)}/10</b>. "
            f"Compliance and professionalism remained measurable areas "
            f"of performance, while empathy should receive additional "
            f"attention where applicable."
        )
        story.append(
            Paragraph(
                conclusion,
                styles["normal"],
            )
        )

        # =====================================================
        # BUILD
        # =====================================================

        document.build(
            story,
            onFirstPage=PDFReportService._header_footer,
            onLaterPages=PDFReportService._header_footer,
        )

        buffer.seek(0)

        return buffer

    # =========================================================
    # RULE PERCENTAGE
    # =========================================================

    @staticmethod
    def _rule_percentage(followed, not_followed):

        try:

            followed = int(followed or 0)
            not_followed = int(not_followed or 0)

            total = followed + not_followed

            if total == 0:
                return "0%"

            return f"{(followed / total) * 100:.1f}%"

        except (TypeError, ValueError):

            return "0%"

    # =========================================================
    # RECOMMENDATIONS
    # =========================================================

    @staticmethod
    def _build_recommendations(report_data):

        summary = report_data.get("summary", {})
        rules = report_data.get("rules", {})
        violations = report_data.get("violations", [])

        recommendations = []

        # Empathy
        empathy = summary.get("average_empathy")

        if empathy is not None:

            try:

                if float(empathy) < 7:

                    recommendations.append(
                        (
                            "High",
                            "Improve empathy and active listening during "
                            "customer interactions, especially when customers "
                            "express financial, emotional, or service-related concerns.",
                        )
                    )

            except (TypeError, ValueError):
                pass

        # Greeting
        greeting_not_followed = int(
            rules.get("greeting_not_followed", 0) or 0
        )

        if greeting_not_followed > 0:

            recommendations.append(
                (
                    "Medium",
                    "Reinforce the standard greeting process and ensure "
                    "agents consistently introduce themselves and establish "
                    "the purpose of the call.",
                )
            )

        # Closing
        closing_not_followed = int(
            rules.get("closing_not_followed", 0) or 0
        )

        if closing_not_followed > 0:

            recommendations.append(
                (
                    "Medium",
                    "Ensure agents provide a clear closing statement, "
                    "confirm that the customer's issue has been addressed, "
                    "and close the interaction professionally.",
                )
            )

        # Violations
        if violations:

            recommendations.append(
                (
                    "Medium",
                    "Review recurring rule violations with agents through "
                    "targeted coaching and call-quality feedback sessions.",
                )
            )

        # Default
        if not recommendations:

            recommendations.append(
                (
                    "Low",
                    "Continue monitoring call quality and maintain regular "
                    "agent coaching based on performance trends.",
                )
            )

        return recommendations