"""add speaker segments to transcripts

Revision ID: 63f81f20d2ce
Revises: 262f2cc3e562
Create Date: 2026-08-05 15:13:15.504656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f81f20d2ce'
down_revision: Union[str, Sequence[str], None] = '262f2cc3e562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('transcripts', sa.Column('speaker_segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'speaker_segments')
