"""analysis use media id

Revision ID: 88ab18bd19a2
Revises: abe89458bdfd
Create Date: 2026-07-21 12:48:45.759933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ab18bd19a2'
down_revision: Union[str, Sequence[str], None] = 'abe89458bdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.drop_table("analysis")

    op.create_table(
        "analysis",

        sa.Column("id", sa.Integer(), primary_key=True),

        sa.Column(
            "media_id",
            sa.Integer(),
            nullable=False
        ),

        sa.Column("summary", sa.Text()),

        sa.Column("sentiment", sa.Text()),

        sa.Column("compliance_score", sa.Float()),

        sa.Column("professionalism_score", sa.Float()),

        sa.Column("empathy_score", sa.Float()),

        sa.Column("overall_score", sa.Float()),

        sa.Column(
            "greeting_followed",
            sa.Boolean(),
            default=False
        ),

        sa.Column(
            "closing_followed",
            sa.Boolean(),
            default=False
        ),

        sa.Column("violations", sa.Text()),

        sa.Column("recommendations", sa.Text()),

        sa.Column("ai_feedback", sa.Text()),

        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),

        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            ondelete="CASCADE",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('transcript_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_transcript_id_fkey'), 'analysis', 'transcripts', ['transcript_id'], ['id'], ondelete='CASCADE')
    op.drop_column('analysis', 'media_id')
    # ### end Alembic commands ###
