"""add provider model language to media

Revision ID: a7a8de6d5716
Revises: 88ab18bd19a2
Create Date: 2026-08-04 12:36:14.912378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a8de6d5716'
down_revision: Union[str, Sequence[str], None] = '88ab18bd19a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analysis_id'), 'analysis', ['id'], unique=False)
    op.add_column('media', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('media', sa.Column('language', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'language')
    op.drop_column('media', 'model')
    op.drop_column('media', 'provider')
    op.drop_index(op.f('ix_analysis_id'), table_name='analysis')
    # ### end Alembic commands ###
