"""add agent id

Revision ID: abe89458bdfd
Revises: de02a31dbee1
Create Date: 2026-07-18 12:48:22.779580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe89458bdfd'
down_revision: Union[str, Sequence[str], None] = 'de02a31dbee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'users', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_column('media', 'agent_id')
    # ### end Alembic commands ###
