"""update_analysis_relationships

Revision ID: fef70fdc1ed5
Revises: 2e9d014c6b0a
Create Date: 2026-07-09 20:44:44.460787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef70fdc1ed5'
down_revision: Union[str, Sequence[str], None] = '2e9d014c6b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('professionalism_score', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('empathy_score', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('analysis', sa.Column('greeting_followed', sa.Boolean(), nullable=True))
    op.add_column('analysis', sa.Column('closing_followed', sa.Boolean(), nullable=True))
    op.add_column('analysis', sa.Column('recommendations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'recommendations')
    op.drop_column('analysis', 'closing_followed')
    op.drop_column('analysis', 'greeting_followed')
    op.drop_column('analysis', 'overall_score')
    op.drop_column('analysis', 'empathy_score')
    op.drop_column('analysis', 'professionalism_score')
    # ### end Alembic commands ###
